services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/attendance_api_development
      RAILS_ENV: development

volumes:
  postgres_data:
  bundle_data: 